# Generated by Django 6.0.6 on 2026-06-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numéro de villa')),
                ('type_villa', models.CharField(choices=[('F4', 'F4 (6 pers. min.)'), ('F5', 'F5 (8 pers. min.)'), ('F6', 'F6 (12 pers. min.)')], max_length=2)),
                ('categorie', models.CharField(choices=[('standard', 'Standard'), ('bord_mer', 'Bord de mer')], max_length=10)),
                ('superficie', models.PositiveIntegerField(help_text='en m²')),
                ('capacite', models.PositiveSmallIntegerField(verbose_name='Capacité (personnes)')),
                ('description', models.TextField(blank=True)),
                ('equipements', models.TextField(blank=True, help_text='Liste des équipements séparés par des virgules')),
                ('disponible_vente', models.BooleanField(default=True)),
                ('disponible_location', models.BooleanField(default=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='villas/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Villa',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TarifLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_villa', models.CharField(choices=[('F4', 'F4 (6 pers. min.)'), ('F5', 'F5 (8 pers. min.)'), ('F6', 'F6 (12 pers. min.)')], max_length=2)),
                ('categorie', models.CharField(choices=[('standard', 'Standard'), ('bord_mer', 'Bord de mer')], max_length=10)),
                ('duree', models.CharField(choices=[('nuit', 'Nuitée'), ('mois', 'Mensuel')], max_length=5)),
                ('prix', models.BigIntegerField(help_text='Prix en FCFA')),
            ],
            options={
                'verbose_name': 'Tarif location',
                'unique_together': {('type_villa', 'categorie', 'duree')},
            },
        ),
        migrations.CreateModel(
            name='TarifVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_villa', models.CharField(choices=[('F4', 'F4 (6 pers. min.)'), ('F5', 'F5 (8 pers. min.)'), ('F6', 'F6 (12 pers. min.)')], max_length=2)),
                ('categorie', models.CharField(choices=[('standard', 'Standard'), ('bord_mer', 'Bord de mer')], max_length=10)),
                ('prix', models.BigIntegerField(help_text='Prix en FCFA')),
            ],
            options={
                'verbose_name': 'Tarif vente VEFA',
                'unique_together': {('type_villa', 'categorie')},
            },
        ),
        migrations.CreateModel(
            name='VillaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='villas/galerie/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='villas.villa')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AppelFonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.PositiveSmallIntegerField(choices=[(1, 'Contrat de réservation'), (2, 'Acte authentique'), (3, 'Fondations'), (4, 'Plancher / RDC'), (5, 'Toiture / étanchéité'), (6, 'Cloisons'), (7, 'Achèvement'), (8, 'Remise des clés')])),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant', models.BigIntegerField(help_text='Montant en FCFA')),
                ('tarif_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_fonds', to='villas.tarifvente')),
            ],
            options={
                'ordering': ['etape'],
                'unique_together': {('tarif_vente', 'etape')},
            },
        ),
    ]
