# Generated by Django 6.0.6 on 2026-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0002_villa_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de la villa'),
        ),
    ]
