# Generated by Django 6.0.6 on 2026-06-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(choices=[('vente_f4', 'Villa à vendre — F4'), ('vente_f5', 'Villa à vendre — F5'), ('vente_f6', 'Villa à vendre — F6'), ('location_nuit', 'Villa à louer — courte durée'), ('location_mois', 'Villa à louer — longue durée'), ('parc', 'Parc aquatique'), ('spa', 'Spa & Massage'), ('autre', 'Autre demande')], max_length=20, verbose_name='Type de bien')),
                ('budget', models.CharField(blank=True, choices=[('moins_175m', 'Moins de 175M FCFA'), ('175_240m', '175M – 240M FCFA'), ('240_320m', '240M – 320M FCFA'), ('plus_320m', 'Plus de 320M FCFA'), ('location', "Location (pas d'achat)")], max_length=20, verbose_name='Budget')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
