# Generated by Django 6.0.6 on 2026-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecontact',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivée'),
        ),
    ]
