# Generated by Django 6.0.6 on 2026-06-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInclus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(help_text="Classe CSS ou nom d'icône (ex: 'pool', 'sports_soccer')", max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service inclus',
                'verbose_name_plural': 'Services inclus',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SoinSpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_soin', models.CharField(choices=[('soin', 'Soin individuel'), ('forfait', 'Forfait')], default='soin', max_length=10)),
                ('nom', models.CharField(max_length=150)),
                ('duree', models.CharField(blank=True, help_text='Ex: 30 min, 1 heure', max_length=50)),
                ('prix_teranga', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('prix_resident', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('contenu', models.TextField(blank=True, help_text='Description du forfait (pour les forfaits uniquement)')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Soin Spa',
                'verbose_name_plural': 'Soins Spa',
                'ordering': ['type_soin', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='TarifParcAquatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('enfant_05', 'Enfants 0–5 ans'), ('enfant_512', 'Enfants 5–12 ans'), ('accompagnant', 'Accompagnant'), ('adolescent', 'Adolescents 12–18 ans'), ('adulte', 'Adultes (+18 ans)'), ('toboggan', 'Toboggans haute attraction'), ('vip', 'Accès VIP')], max_length=20, unique=True)),
                ('prix_visiteur', models.PositiveIntegerField(help_text='Prix en FCFA (0 = gratuit)')),
                ('prix_resident', models.PositiveIntegerField(help_text='Prix en FCFA (0 = gratuit)')),
                ('gratuit', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tarif parc aquatique',
                'verbose_name_plural': 'Tarifs parc aquatique',
            },
        ),
    ]
